export const nations = {
    ESP: { name: 'Spain', code: 'es' },
    ARG: { name: 'Argentina', code: 'ar' },
    BRA: { name: 'Brazil', code: 'br' },
    FRA: { name: 'France', code: 'fr' },
    GER: { name: 'Germany', code: 'de' },
    ITA: { name: 'Italy', code: 'it' },
    ENG: { name: 'England', code: 'eng' },
    MAR: { name: 'Morocco', code: 'ma' },
    NGA: { name: 'Nigeria', code: 'ng' },
    AUT: { name: 'Austria', code: 'at' },
    POR: { name: 'Portugal', code: 'pt' },
    URU: { name: 'Uruguay', code: 'uy' },
    VEN: { name: 'Venezuela', code: 've' },
    HON: { name: 'Honduras', code: 'hn' },
    JPN: { name: 'Japan', code: 'jp' },
    COL: { name: 'Colombia', code: 'co' },
    CIV: { name: 'Ivory Coast', code: 'ci' },
    COD: { name: 'DR Congo', code: 'cd' },
    ALB: { name: 'Albania', code: 'al' },
    SWE: { name: 'Sweden', code: 'se' },
    SUR: { name: 'Suriname', code: 'sr' },
    NED: { name: 'Nederland', code: 'nl' },
    NIG: { name: 'Niger', code: 'ne' },
    CMR: { name: 'Cameroon', code: 'cm' },
    CRO: { name: 'Croatia', code: 'hr' },
    CAN: { name: 'Canada', code: 'ca' },
    MTN: { name: 'Mauritania', code: 'mr' },
    USA: { name: 'United States of America', code: 'us' },
    ANG: { name: 'Angola', code: 'ao' },
    DEN: { name: 'Denmark', code: 'dk' },
    SEN: { name: 'Senegal', code: 'sn' },
    BEL: { name: 'Belgium', code: 'be' },
    GUI: { name: 'Guinea', code: 'gn' },
    MLI: { name: 'Mali', code: 'ml' },
    TOG: { name: 'Togo', code: 'tg' },
    SRB: { name: 'Serbia', code: 'rs' },
    DOM: { name: 'Dominican Republic', code: 'do' },
    MAS: { name: 'Malaysia', code: 'my' },
    TUR: { name: 'Turkey', code: 'tr' },
    SVK: { name: 'Slovakia', code: 'sk' },
    CTA: { name: 'Central African Republic', code: 'cf' },
    UKR: { name: 'Ukraine', code: 'ua' },
    CZE: { name: 'Czech Republic', code: 'cz' },
    POL: { name: 'Poland', code: 'pl' },
    EQG: { name: 'Equatorial Guinea', code: 'gq' },
    GEO: { name: 'Georgia', code: 'ge' },
    MKD: { name: 'North Macedonia', code: 'mk' },
    KVX: { name: 'Kosovo', code: 'xk' },
    NOR: { name: 'Norway', code: 'no' },
    SVN: { name: 'Slovenia', code: 'si' },
    GHA: { name: 'Ghana', code: 'gh' },
    ROU: { name: 'Romania', code: 'ro' },
    ALG: { name: 'Algeria', code: 'dz' },
    SUI: { name: 'Switzerland', code: 'ch' },
    AUS: { name: 'Australia', code: 'au' },
    CHI: { name: 'Chile', code: 'cl' },
    ISR: { name: 'Israel', code: 'il' },
    ISL: { name: 'Iceland', code: 'is' },
    GRE: { name: 'Greece', code: 'gr' },
    RUS: { name: 'Russia', code: 'ru' }
};

export function getNationName(nation) {
    const code = nation.split(' ')[1];

    return nations[code]?.name || nation;
}

